/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aircraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all aircraft */
        get: operations["listAircraft"];
        put?: never;
        /** Create a new aircraft */
        post: operations["createAircraft"];
        /** Delete all aircraft */
        delete: operations["deleteAllAircraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/aircraft/{aircraftSpec}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aircraft by ID or registration */
        get: operations["getAircraft"];
        put?: never;
        post?: never;
        /** Delete an aircraft */
        delete: operations["deleteAircraft"];
        options?: never;
        head?: never;
        /** Update aircraft */
        patch: operations["updateAircraft"];
        trace?: never;
    };
    "/airlines/{airlineSpec}/aircraft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all aircraft owned by an airline */
        get: operations["listAircraftByAirline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all airports */
        get: operations["listAirports"];
        put?: never;
        /** Create a new airport */
        post: operations["createAirport"];
        /** Delete all airports */
        delete: operations["deleteAllAirports"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airports/{airportSpec}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get airport by ID or IATA code */
        get: operations["getAirport"];
        put?: never;
        post?: never;
        /** Delete an airport */
        delete: operations["deleteAirport"];
        options?: never;
        head?: never;
        /** Update airport */
        patch: operations["updateAirport"];
        trace?: never;
    };
    "/airports/{airportSpec}/flight-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List flight schedules that depart from or arrive at an airport */
        get: operations["listFlightSchedulesByAirport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all airlines */
        get: operations["listAirlines"];
        put?: never;
        /** Create a new airline */
        post: operations["createAirline"];
        /** Delete all airlines */
        delete: operations["deleteAllAirlines"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/airlines/{airlineSpec}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get airline by ID or IATA code */
        get: operations["getAirline"];
        put?: never;
        post?: never;
        /** Delete an airline */
        delete: operations["deleteAirline"];
        options?: never;
        head?: never;
        /** Update airline */
        patch: operations["updateAirline"];
        trace?: never;
    };
    "/airlines/{airlineSpec}/flight-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List flight schedules for an airline */
        get: operations["listFlightSchedulesByAirline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flight-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all flight schedules */
        get: operations["listFlightSchedules"];
        put?: never;
        /** Create a new flight schedule */
        post: operations["createFlightSchedule"];
        /** Delete all flight schedules */
        delete: operations["deleteAllFlightSchedules"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flight-schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get flight schedule by ID */
        get: operations["getFlightSchedule"];
        put?: never;
        post?: never;
        /** Delete a flight schedule */
        delete: operations["deleteFlightSchedule"];
        options?: never;
        head?: never;
        /** Update flight schedule */
        patch: operations["updateFlightSchedule"];
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all routes */
        get: operations["listRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{route}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get route by IATA codes of origin and destination airports */
        get: operations["getRoute"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AircraftID: number;
        /** @description Registration code for an aircraft. See https://en.wikipedia.org/wiki/List_of_aircraft_registration_prefixes. */
        AircraftRegistration: string;
        AircraftSpec: components["schemas"]["AircraftID"] | components["schemas"]["AircraftRegistration"];
        Aircraft: {
            id: number;
            registration: components["schemas"]["AircraftRegistration"];
            aircraftType: components["schemas"]["AircraftTypeIATACode"];
            airline: components["schemas"]["Airline"];
        };
        /** @description IATA aircraft type code for an aircraft. See https://en.wikipedia.org/wiki/List_of_aircraft_type_designators. */
        AircraftTypeIATACode: string;
        AirlineID: number;
        /** @description IATA code for airline */
        AirlineIATACode: string;
        AirlineSpec: components["schemas"]["AirlineID"] | components["schemas"]["AirlineIATACode"];
        Airline: {
            id: number;
            iataCode: components["schemas"]["AirlineIATACode"];
            name: string;
        };
        AirportID: number;
        /** @description IATA code for airport */
        AirportIATACode: string;
        AirportSpec: components["schemas"]["AirportID"] | components["schemas"]["AirportIATACode"];
        Airport: {
            id: number;
            name: string;
            iataCode: components["schemas"]["AirportIATACode"];
            country: string;
            region: string;
            point: components["schemas"]["Point"];
        };
        Point: {
            /** Format: double */
            longitude: number;
            /** Format: double */
            latitude: number;
        };
        FlightSchedule: {
            id: number;
            airline: components["schemas"]["Airline"];
            number: components["schemas"]["FlightNumber"];
            originAirport: components["schemas"]["Airport"];
            destinationAirport: components["schemas"]["Airport"];
            /** Format: double */
            distanceMiles?: number;
            published: boolean;
        };
        FlightNumber: string;
        Route: {
            originAirport: components["schemas"]["Airport"];
            destinationAirport: components["schemas"]["Airport"];
            /** Format: double */
            distanceMiles?: number;
            flightSchedulesCount: number;
        };
    };
    responses: never;
    parameters: {
        aircraftSpec: components["schemas"]["AircraftSpec"];
        airportSpec: components["schemas"]["AirportSpec"];
        airlineSpec: components["schemas"]["AirlineSpec"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                    };
                };
            };
        };
    };
    listAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of aircraft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"][];
                };
            };
        };
    };
    createAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    registration: components["schemas"]["AircraftRegistration"];
                    aircraftType: components["schemas"]["AircraftTypeIATACode"];
                    airline: components["schemas"]["AirlineSpec"];
                };
            };
        };
        responses: {
            /** @description Aircraft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAllAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All aircraft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aircraftSpec: components["parameters"]["aircraftSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aircraft found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"];
                };
            };
            /** @description Aircraft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aircraftSpec: components["parameters"]["aircraftSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aircraft deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aircraft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAircraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aircraftSpec: components["parameters"]["aircraftSpec"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    registration?: components["schemas"]["AircraftRegistration"];
                    aircraftType?: components["schemas"]["AircraftTypeIATACode"];
                    airline?: components["schemas"]["AirlineSpec"];
                };
            };
        };
        responses: {
            /** @description Aircraft updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"];
                };
            };
            /** @description Aircraft not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAircraftByAirline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airlineSpec: components["parameters"]["airlineSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of aircraft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Aircraft"][];
                };
            };
            /** @description Airline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAirports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of airports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airport"][];
                };
            };
        };
    };
    createAirport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    iataCode: components["schemas"]["AirportIATACode"];
                };
            };
        };
        responses: {
            /** @description Airport created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airport"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAllAirports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All airports deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAirport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airportSpec: components["parameters"]["airportSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airport"];
                };
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAirport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airportSpec: components["parameters"]["airportSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airport deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAirport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airportSpec: components["parameters"]["airportSpec"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    iataCode?: components["schemas"]["AirportIATACode"];
                };
            };
        };
        responses: {
            /** @description Airport updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airport"];
                };
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFlightSchedulesByAirport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airportSpec: components["parameters"]["airportSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight schedules by airport */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSchedule"][];
                };
            };
            /** @description Airport not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAirlines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of airlines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airline"][];
                };
            };
        };
    };
    createAirline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    iataCode: components["schemas"]["AirlineIATACode"];
                    name: string;
                };
            };
        };
        responses: {
            /** @description Airline created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airline"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAllAirlines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All airlines deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAirline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airlineSpec: components["parameters"]["airlineSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airline found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airline"];
                };
            };
            /** @description Airline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAirline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airlineSpec: components["schemas"]["AirlineSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Airline deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Airline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAirline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airlineSpec: components["parameters"]["airlineSpec"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    iataCode?: components["schemas"]["AirlineIATACode"];
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Airline updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Airline"];
                };
            };
            /** @description Airline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFlightSchedulesByAirline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                airlineSpec: components["parameters"]["airlineSpec"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight schedules by airline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSchedule"][];
                };
            };
            /** @description Airline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFlightSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of flight schedules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSchedule"][];
                };
            };
        };
    };
    createFlightSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    airline: components["schemas"]["AirlineSpec"];
                    number: components["schemas"]["FlightNumber"];
                    originAirport: components["schemas"]["AirportSpec"];
                    destinationAirport: components["schemas"]["AirportSpec"];
                    /** @default false */
                    published?: boolean;
                };
            };
        };
        responses: {
            /** @description Flight schedule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSchedule"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAllFlightSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All flight schedules deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFlightSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight schedule found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSchedule"];
                };
            };
            /** @description Flight schedule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFlightSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flight schedule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Flight schedule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateFlightSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    airline?: components["schemas"]["AirlineSpec"];
                    number?: components["schemas"]["FlightNumber"];
                    originAirport?: components["schemas"]["AirportSpec"];
                    destinationAirport?: components["schemas"]["AirportSpec"];
                    published?: boolean;
                };
            };
        };
        responses: {
            /** @description Flight schedule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlightSchedule"];
                };
            };
            /** @description Flight schedule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of routes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"][];
                };
            };
        };
    };
    getRoute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Route information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Route not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
