package main

import (
	"context"
	"fmt"

	"github.com/stellora/airline/api-server/api"
)

func insertSampleData(ctx context.Context, handler *Handler) error {
	airports := []string{"SFO", "SIN", "NRT", "HND", "EWR", "LAX", "DEN", "ORD", "AMS", "LHR", "HKG", "SYD", "HNL", "LIH", "SJC", "STS", "SEA", "FRA", "MUC", "DXB", "TLV", "IST", "DOH", "KIX", "MEL", "JNB", "CPT", "EZE", "MEX", "CUN", "MSP", "IAD", "DCA", "DFW", "MRS", "PVR", "BOS", "FCO", "SCL", "CDG", "ICN", "PVG", "HYD", "DEL", "BOM", "BLR", "PEK"}
	if _, err := insertAirportsWithIATACodes(ctx, handler, airports...); err != nil {
		return err
	}

	airlines := map[string]string{
		"UA": "United Airlines",
		"SQ": "Singapore Airlines",
		"LH": "Lufthansa",
		"BA": "British Airways",
		"DL": "Delta Air Lines",
		"AF": "Air France",
		"KL": "KLM Royal Dutch Airlines",
		"LX": "Swiss International Air Lines",
		"EY": "Etihad Airways",
		"EK": "Emirates",
		"QR": "Qatar Airways",
		"QF": "Qantas",
		"NZ": "Air New Zealand",
	}
	if _, err := insertAirlines(ctx, handler, airlines); err != nil {
		return err
	}

	// See https://sites.google.com/site/unitedfleetsite/mainline-fleet-tracking for UA fleet data.
	ua := api.NewAirlineSpec(0, "UA")
	aircraft := []api.CreateAircraftJSONRequestBody{
		{Registration: "N27251", AircraftType: "B38M", Airline: ua},
		{Registration: "N27252", AircraftType: "B38M", Airline: ua},
		{Registration: "N27253", AircraftType: "B38M", Airline: ua},
		{Registration: "N27254", AircraftType: "B38M", Airline: ua},
		{Registration: "N27255", AircraftType: "B38M", Airline: ua},
		{Registration: "N27256", AircraftType: "B38M", Airline: ua},
		{Registration: "N27257", AircraftType: "B38M", Airline: ua},
		{Registration: "N27258", AircraftType: "B38M", Airline: ua},
		{Registration: "N27259", AircraftType: "B38M", Airline: ua},
		{Registration: "N27260", AircraftType: "B38M", Airline: ua},
		{Registration: "N27261", AircraftType: "B38M", Airline: ua},
		{Registration: "N27262", AircraftType: "B38M", Airline: ua},
		{Registration: "N27263", AircraftType: "B38M", Airline: ua},
		{Registration: "N27264", AircraftType: "B38M", Airline: ua},
		{Registration: "N27265", AircraftType: "B38M", Airline: ua},
		{Registration: "N27266", AircraftType: "B38M", Airline: ua},
		{Registration: "N27267", AircraftType: "B38M", Airline: ua},
		{Registration: "N27268", AircraftType: "B38M", Airline: ua},
		{Registration: "N27269", AircraftType: "B38M", Airline: ua},
		{Registration: "N27270", AircraftType: "B38M", Airline: ua},
		{Registration: "N27271", AircraftType: "B38M", Airline: ua},
		{Registration: "N27272", AircraftType: "B38M", Airline: ua},
		{Registration: "N27273", AircraftType: "B38M", Airline: ua},
		{Registration: "N27274", AircraftType: "B38M", Airline: ua},
		{Registration: "N47275", AircraftType: "B38M", Airline: ua},
		{Registration: "N27276", AircraftType: "B38M", Airline: ua},
		{Registration: "N37278", AircraftType: "B38M", Airline: ua},

		{Registration: "N2331U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2332U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2333U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2534U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2135U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2136U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2737U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2138U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2639U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2140U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2341U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2142U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2243U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2644U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2645U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2846U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2747U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2748U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2749U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2250U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2251U", AircraftType: "B77W", Airline: ua},
		{Registration: "N2352U", AircraftType: "B77W", Airline: ua},

		{Registration: "N27901", AircraftType: "B788", Airline: ua},
		{Registration: "N26902", AircraftType: "B788", Airline: ua},
		{Registration: "N27903", AircraftType: "B788", Airline: ua},
		{Registration: "N20904", AircraftType: "B788", Airline: ua},
		{Registration: "N45905", AircraftType: "B788", Airline: ua},
		{Registration: "N26906", AircraftType: "B788", Airline: ua},
		{Registration: "N29907", AircraftType: "B788", Airline: ua},
		{Registration: "N27908", AircraftType: "B788", Airline: ua},
		{Registration: "N26909", AircraftType: "B788", Airline: ua},
		{Registration: "N26910", AircraftType: "B788", Airline: ua},
		{Registration: "N28912", AircraftType: "B788", Airline: ua},
		{Registration: "N30913", AircraftType: "B788", Airline: ua},

		{Registration: "N38950", AircraftType: "B789", Airline: ua},
		{Registration: "N19951", AircraftType: "B789", Airline: ua},
		{Registration: "N26952", AircraftType: "B789", Airline: ua},
		{Registration: "N35953", AircraftType: "B789", Airline: ua},
		{Registration: "N13954", AircraftType: "B789", Airline: ua},
		{Registration: "N38955", AircraftType: "B789", Airline: ua},
		{Registration: "N45956", AircraftType: "B789", Airline: ua},
		{Registration: "N27957", AircraftType: "B789", Airline: ua},
		{Registration: "N27958", AircraftType: "B789", Airline: ua},
		{Registration: "N27959", AircraftType: "B789", Airline: ua},
		{Registration: "N26960", AircraftType: "B789", Airline: ua},
		{Registration: "N29961", AircraftType: "B789", Airline: ua},
		{Registration: "N36962", AircraftType: "B789", Airline: ua},
		{Registration: "N17963", AircraftType: "B789", Airline: ua},
		{Registration: "N27964", AircraftType: "B789", Airline: ua},
		{Registration: "N27965", AircraftType: "B789", Airline: ua},
		{Registration: "N26966", AircraftType: "B789", Airline: ua},
		{Registration: "N26967", AircraftType: "B789", Airline: ua},
		{Registration: "N29968", AircraftType: "B789", Airline: ua},
		{Registration: "N15969", AircraftType: "B789", Airline: ua},
		{Registration: "N26970", AircraftType: "B789", Airline: ua},
		{Registration: "N29971", AircraftType: "B789", Airline: ua},
		{Registration: "N24972", AircraftType: "B789", Airline: ua},
		{Registration: "N24973", AircraftType: "B789", Airline: ua},
		{Registration: "N24974", AircraftType: "B789", Airline: ua},
		{Registration: "N29975", AircraftType: "B789", Airline: ua},
		{Registration: "N24976", AircraftType: "B789", Airline: ua},
		{Registration: "N29977", AircraftType: "B789", Airline: ua},
		{Registration: "N29978", AircraftType: "B789", Airline: ua},
		{Registration: "N24979", AircraftType: "B789", Airline: ua},
		{Registration: "N24980", AircraftType: "B789", Airline: ua},
		{Registration: "N29981", AircraftType: "B789", Airline: ua},
		{Registration: "N25982", AircraftType: "B789", Airline: ua},
		{Registration: "N23983", AircraftType: "B789", Airline: ua},
		{Registration: "N29984", AircraftType: "B789", Airline: ua},
		{Registration: "N29985", AircraftType: "B789", Airline: ua},
		{Registration: "N19986", AircraftType: "B789", Airline: ua},
		{Registration: "N28987", AircraftType: "B789", Airline: ua},
		{Registration: "N24988", AircraftType: "B789", Airline: ua},
		{Registration: "N29989", AircraftType: "B789", Airline: ua},
		{Registration: "N24990", AircraftType: "B789", Airline: ua},

		{Registration: "N14001", AircraftType: "B78X", Airline: ua},
		{Registration: "N17002", AircraftType: "B78X", Airline: ua},
		{Registration: "N12003", AircraftType: "B78X", Airline: ua},
		{Registration: "N12004", AircraftType: "B78X", Airline: ua},
		{Registration: "N12005", AircraftType: "B78X", Airline: ua},
		{Registration: "N12006", AircraftType: "B78X", Airline: ua},
		{Registration: "N91007", AircraftType: "B78X", Airline: ua},
		{Registration: "N16008", AircraftType: "B78X", Airline: ua},
		{Registration: "N16009", AircraftType: "B78X", Airline: ua},
		{Registration: "N12010", AircraftType: "B78X", Airline: ua},
		{Registration: "N14011", AircraftType: "B78X", Airline: ua},
		{Registration: "N12012", AircraftType: "B78X", Airline: ua},
		{Registration: "N13013", AircraftType: "B78X", Airline: ua},
		{Registration: "N13014", AircraftType: "B78X", Airline: ua},
		{Registration: "N17015", AircraftType: "B78X", Airline: ua},
		{Registration: "N14016", AircraftType: "B78X", Airline: ua},
		{Registration: "N17017", AircraftType: "B78X", Airline: ua},
		{Registration: "N13018", AircraftType: "B78X", Airline: ua},
		{Registration: "N14019", AircraftType: "B78X", Airline: ua},
		{Registration: "N12020", AircraftType: "B78X", Airline: ua},
		{Registration: "N12021", AircraftType: "B78X", Airline: ua},

		{Registration: "9V-SJG", AircraftType: "A359", Airline: api.NewAirlineSpec(0, "SQ")},
		{Registration: "9V-SJI", AircraftType: "A359", Airline: api.NewAirlineSpec(0, "SQ")},
		{Registration: "9V-SNC", AircraftType: "B77W", Airline: api.NewAirlineSpec(0, "SQ")},

		{Registration: "D-ABVM", AircraftType: "B744", Airline: api.NewAirlineSpec(0, "LH")},
		{Registration: "D-AIXF", AircraftType: "A359", Airline: api.NewAirlineSpec(0, "LH")},
		{Registration: "D-ABYU", AircraftType: "B748", Airline: api.NewAirlineSpec(0, "LH")},
		{Registration: "D-AIXJ", AircraftType: "A359", Airline: api.NewAirlineSpec(0, "LH")},
	}
	for _, a := range aircraft {
		if _, err := handler.CreateAircraft(ctx, api.CreateAircraftRequestObject{Body: &a}); err != nil {
			return err
		}
	}

	flightSchedules := []*api.CreateFlightScheduleJSONRequestBody{
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "SIN"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 2, 4, 6},
			DepartureTime:      "23:35",
			ArrivalTime:        "06:15",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "2",
			OriginAirport:      api.NewAirportSpec(0, "SIN"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{1, 3, 5, 0},
			DepartureTime:      "10:10",
			ArrivalTime:        "09:20",
		},
		{
			Airline:            api.NewAirlineSpec(0, "SQ"),
			Number:             "33",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "SIN"),
			AircraftType:       "A359",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{1, 3, 5, 0},
			DepartureTime:      "22:35",
			ArrivalTime:        "05:15",
		},
		{
			Airline:            api.NewAirlineSpec(0, "SQ"),
			Number:             "34",
			OriginAirport:      api.NewAirportSpec(0, "SIN"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "A359",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{1, 3, 5, 0},
			DepartureTime:      "09:20",
			ArrivalTime:        "08:45",
		},
		{
			Airline:            api.NewAirlineSpec(0, "SQ"),
			Number:             "31",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "SIN"),
			AircraftType:       "A359",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 2, 4, 6},
			DepartureTime:      "20:35",
			ArrivalTime:        "03:15",
		},
		{
			Airline:            api.NewAirlineSpec(0, "SQ"),
			Number:             "32",
			OriginAirport:      api.NewAirportSpec(0, "SIN"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "A359",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{1, 3, 5, 0},
			DepartureTime:      "07:20",
			ArrivalTime:        "06:45",
		},
		{
			Airline:            api.NewAirlineSpec(0, "SQ"),
			Number:             "345",
			OriginAirport:      api.NewAirportSpec(0, "ZRH"),
			DestinationAirport: api.NewAirportSpec(0, "SIN"),
			AircraftType:       "B77W",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{1, 3, 5, 0},
			DepartureTime:      "11:45",
			ArrivalTime:        "05:55",
		},
		{
			Airline:            api.NewAirlineSpec(0, "SQ"),
			Number:             "346",
			OriginAirport:      api.NewAirportSpec(0, "SIN"),
			DestinationAirport: api.NewAirportSpec(0, "ZRH"),
			AircraftType:       "B77W",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{1, 3, 5, 0},
			DepartureTime:      "01:30",
			ArrivalTime:        "08:15",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "2168",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "EWR"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "13:30",
			ArrivalTime:        "22:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1054",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "EWR"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "06:30",
			ArrivalTime:        "15:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "2460",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "EWR"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "22:30",
			ArrivalTime:        "07:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "2855",
			OriginAirport:      api.NewAirportSpec(0, "EWR"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "17:30",
			ArrivalTime:        "21:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "598",
			OriginAirport:      api.NewAirportSpec(0, "EWR"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "08:30",
			ArrivalTime:        "12:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1579",
			OriginAirport:      api.NewAirportSpec(0, "EWR"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "19:30",
			ArrivalTime:        "23:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1684",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "LIH"),
			AircraftType:       "B38M",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 2, 4, 6},
			DepartureTime:      "23:35",
			ArrivalTime:        "06:15",
		},

		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1563",
			OriginAirport:      api.NewAirportSpec(0, "LIH"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B38M",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 2, 4, 6},
			DepartureTime:      "07:30",
			ArrivalTime:        "14:10",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1111",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "LIH"),
			AircraftType:       "B38M",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "11:00",
			ArrivalTime:        "17:40",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "863",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "SYD"),
			AircraftType:       "B789",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "22:45",
			ArrivalTime:        "06:30",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "830",
			OriginAirport:      api.NewAirportSpec(0, "SYD"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B789",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "11:30",
			ArrivalTime:        "07:15",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "5703",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "MSP"),
			AircraftType:       "A320",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "08:30",
			ArrivalTime:        "14:15",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "5297",
			OriginAirport:      api.NewAirportSpec(0, "MSP"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "A320",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "15:30",
			ArrivalTime:        "17:45",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "14",
			OriginAirport:      api.NewAirportSpec(0, "EWR"),
			DestinationAirport: api.NewAirportSpec(0, "LHR"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "18:30",
			ArrivalTime:        "06:30",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "110",
			OriginAirport:      api.NewAirportSpec(0, "EWR"),
			DestinationAirport: api.NewAirportSpec(0, "LHR"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "22:30",
			ArrivalTime:        "10:30",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "59",
			OriginAirport:      api.NewAirportSpec(0, "FRA"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B78X",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "10:15",
			ArrivalTime:        "13:45",
		},
		{
			Airline:            api.NewAirlineSpec(0, "KL"),
			Number:             "1823",
			OriginAirport:      api.NewAirportSpec(0, "AMS"),
			DestinationAirport: api.NewAirportSpec(0, "FRA"),
			AircraftType:       "B738",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "07:45",
			ArrivalTime:        "09:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "BA"),
			Number:             "430",
			OriginAirport:      api.NewAirportSpec(0, "LHR"),
			DestinationAirport: api.NewAirportSpec(0, "AMS"),
			AircraftType:       "A320",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "06:45",
			ArrivalTime:        "09:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "344",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "DFW"),
			AircraftType:       "A320",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "09:30",
			ArrivalTime:        "15:00",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "271",
			OriginAirport:      api.NewAirportSpec(0, "DFW"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "A320",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "16:30",
			ArrivalTime:        "18:45",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "1954",
			OriginAirport:      api.NewAirportSpec(0, "SFO"),
			DestinationAirport: api.NewAirportSpec(0, "DCA"),
			AircraftType:       "B738",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "13:30",
			ArrivalTime:        "21:45",
		},
		{
			Airline:            api.NewAirlineSpec(0, "UA"),
			Number:             "395",
			OriginAirport:      api.NewAirportSpec(0, "DCA"),
			DestinationAirport: api.NewAirportSpec(0, "SFO"),
			AircraftType:       "B738",
			StartDate:          "2025-01-01",
			EndDate:            "2025-02-07",
			DaysOfWeek:         []int{0, 1, 2, 3, 4, 5, 6},
			DepartureTime:      "07:30",
			ArrivalTime:        "10:45",
		},
	}
	for _, f := range flightSchedules {
		f.Published = ptrTo(true)
	}
	for _, f := range flightSchedules {
		if _, err := handler.CreateFlightSchedule(ctx, api.CreateFlightScheduleRequestObject{Body: f}); err != nil {
			return fmt.Errorf("inserting flight schedule: %w", err)
		}
	}

	return nil
}
