// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/stellora/airline/api-server/localtime"
	"github.com/stellora/airline/api-server/zonedtime"
)

type Aircraft struct {
	ID           int64
	Registration string
	AircraftType string
	AirlineID    int64
}

type AircraftView struct {
	ID              int64
	Registration    string
	AircraftType    string
	AirlineID       int64
	AirlineIataCode string
	AirlineName     string
}

type Airline struct {
	ID       int64
	IataCode string
	Name     string
}

type Airport struct {
	ID       int64
	IataCode string
	OadbID   sql.NullInt64
}

type Fleet struct {
	ID          int64
	AirlineID   int64
	Code        string
	Description string
}

type FleetsAircraft struct {
	FleetID    int64
	AircraftID int64
}

type FleetsView struct {
	ID              int64
	AirlineID       int64
	Code            string
	Description     string
	AirlineIataCode string
	AirlineName     string
}

type Flight struct {
	ID                              int64
	SourceScheduleID                sql.NullInt64
	SourceScheduleInstanceLocaldate *localtime.LocalDate
	AirlineID                       int64
	Number                          string
	OriginAirportID                 int64
	DestinationAirportID            int64
	FleetID                         int64
	AircraftID                      sql.NullInt64
	DepartureDatetime               *zonedtime.ZonedTime
	ArrivalDatetime                 *zonedtime.ZonedTime
	DepartureDatetimeUtc            time.Time
	ArrivalDatetimeUtc              time.Time
	Notes                           string
	Published                       bool
}

type FlightsView struct {
	ID                              int64
	SourceScheduleID                sql.NullInt64
	SourceScheduleInstanceLocaldate *localtime.LocalDate
	AirlineID                       int64
	Number                          string
	OriginAirportID                 int64
	DestinationAirportID            int64
	FleetID                         int64
	AircraftID                      sql.NullInt64
	DepartureDatetime               zonedtime.ZonedTime
	ArrivalDatetime                 zonedtime.ZonedTime
	DepartureDatetimeUtc            time.Time
	ArrivalDatetimeUtc              time.Time
	Notes                           string
	Published                       bool
	AirlineIataCode                 string
	AirlineName                     string
	FleetAirlineID                  int64
	FleetCode                       string
	FleetDescription                string
	OriginAirportIataCode           string
	OriginAirportOadbID             sql.NullInt64
	DestinationAirportIataCode      string
	DestinationAirportOadbID        sql.NullInt64
	AircraftRegistration            sql.NullString
	AircraftAircraftType            sql.NullString
	AircraftAirlineID               sql.NullInt64
	AircraftAirlineIataCode         sql.NullString
	AircraftAirlineName             sql.NullString
}

type Itinerary struct {
	ID       int64
	RecordID string
}

type Passenger struct {
	ID   int64
	Name string
}

type Route struct {
	OriginAirportID            int64
	DestinationAirportID       int64
	OriginAirportIataCode      string
	OriginAirportOadbID        sql.NullInt64
	DestinationAirportIataCode string
	DestinationAirportOadbID   sql.NullInt64
	SchedulesCount             int64
}

type Schedule struct {
	ID                   int64
	AirlineID            int64
	Number               string
	OriginAirportID      int64
	DestinationAirportID int64
	FleetID              int64
	StartLocaldate       *localtime.LocalDate
	EndLocaldate         *localtime.LocalDate
	DaysOfWeek           string
	DepartureLocaltime   *localtime.TimeOfDay
	DurationSec          int64
	Published            bool
}

type SchedulesView struct {
	ID                         int64
	AirlineID                  int64
	Number                     string
	OriginAirportID            int64
	DestinationAirportID       int64
	FleetID                    int64
	StartLocaldate             localtime.LocalDate
	EndLocaldate               localtime.LocalDate
	DaysOfWeek                 string
	DepartureLocaltime         localtime.TimeOfDay
	DurationSec                int64
	Published                  bool
	AirlineIataCode            string
	AirlineName                string
	FleetAirlineID             int64
	FleetCode                  string
	FleetDescription           string
	OriginAirportIataCode      string
	OriginAirportOadbID        sql.NullInt64
	DestinationAirportIataCode string
	DestinationAirportOadbID   sql.NullInt64
}

type SeatAssignment struct {
	ID          int64
	SegmentID   int64
	FlightID    int64
	PassengerID int64
	Seat        string
}

type SeatAssignmentsView struct {
	ID                int64
	SegmentID         int64
	FlightID          int64
	PassengerID       int64
	Seat              string
	ItineraryID       int64
	ItineraryRecordID string
	PassengerName     string
}

type Segment struct {
	ID           int64
	ItineraryID  int64
	FlightID     int64
	PassengerID  int64
	BookingClass string
}

type SegmentsView struct {
	ID                int64
	ItineraryID       int64
	FlightID          int64
	PassengerID       int64
	BookingClass      string
	ItineraryRecordID string
	PassengerName     string
}

type Ticket struct {
	ID          int64
	Number      string
	ItineraryID int64
	PassengerID int64
	FareBasis   string
}
