// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/stellora/airline/api-server/localtime"
	"github.com/stellora/airline/api-server/zonedtime"
)

type Aircraft struct {
	ID           int64
	Registration string
	AircraftType string
	AirlineID    int64
}

type AircraftView struct {
	ID              int64
	Registration    string
	AircraftType    string
	AirlineID       int64
	AirlineIataCode string
	AirlineName     string
}

type Airline struct {
	ID       int64
	IataCode string
	Name     string
}

type Airport struct {
	ID       int64
	IataCode string
	OadbID   sql.NullInt64
}

type FlightInstance struct {
	ID                                    int64
	SourceFlightScheduleID                sql.NullInt64
	SourceFlightScheduleInstanceLocaldate *localtime.LocalDate
	AirlineID                             int64
	Number                                string
	OriginAirportID                       int64
	DestinationAirportID                  int64
	AircraftType                          string
	AircraftID                            sql.NullInt64
	DepartureDatetime                     *zonedtime.ZonedTime
	ArrivalDatetime                       *zonedtime.ZonedTime
	DepartureDatetimeUtc                  time.Time
	ArrivalDatetimeUtc                    time.Time
	Notes                                 string
	Published                             bool
}

type FlightInstancesView struct {
	ID                                    int64
	SourceFlightScheduleID                sql.NullInt64
	SourceFlightScheduleInstanceLocaldate *localtime.LocalDate
	AirlineID                             int64
	Number                                string
	OriginAirportID                       int64
	DestinationAirportID                  int64
	AircraftType                          string
	AircraftID                            sql.NullInt64
	DepartureDatetime                     zonedtime.ZonedTime
	ArrivalDatetime                       zonedtime.ZonedTime
	DepartureDatetimeUtc                  time.Time
	ArrivalDatetimeUtc                    time.Time
	Notes                                 string
	Published                             bool
	AirlineIataCode                       string
	AirlineName                           string
	OriginAirportIataCode                 string
	OriginAirportOadbID                   sql.NullInt64
	DestinationAirportIataCode            string
	DestinationAirportOadbID              sql.NullInt64
	AircraftRegistration                  sql.NullString
	AircraftAircraftType                  sql.NullString
	AircraftAirlineID                     sql.NullInt64
	AircraftAirlineIataCode               sql.NullString
	AircraftAirlineName                   sql.NullString
}

type FlightSchedule struct {
	ID                   int64
	AirlineID            int64
	Number               string
	OriginAirportID      int64
	DestinationAirportID int64
	AircraftType         string
	StartLocaldate       *localtime.LocalDate
	EndLocaldate         *localtime.LocalDate
	DaysOfWeek           string
	DepartureLocaltime   *localtime.TimeOfDay
	DurationSec          int64
	Published            bool
}

type FlightSchedulesView struct {
	ID                         int64
	AirlineID                  int64
	Number                     string
	OriginAirportID            int64
	DestinationAirportID       int64
	AircraftType               string
	StartLocaldate             localtime.LocalDate
	EndLocaldate               localtime.LocalDate
	DaysOfWeek                 string
	DepartureLocaltime         localtime.TimeOfDay
	DurationSec                int64
	Published                  bool
	AirlineIataCode            string
	AirlineName                string
	OriginAirportIataCode      string
	OriginAirportOadbID        sql.NullInt64
	DestinationAirportIataCode string
	DestinationAirportOadbID   sql.NullInt64
}

type Itinerary struct {
	ID       int64
	RecordID string
}

type ItineraryFlight struct {
	ItineraryID      int64
	FlightInstanceID int64
}

type ItineraryPassenger struct {
	ItineraryID int64
	PassengerID int64
}

type Passenger struct {
	ID   int64
	Name string
}

type Route struct {
	OriginAirportID            int64
	DestinationAirportID       int64
	OriginAirportIataCode      string
	OriginAirportOadbID        sql.NullInt64
	DestinationAirportIataCode string
	DestinationAirportOadbID   sql.NullInt64
	FlightSchedulesCount       int64
}

type SeatAssignment struct {
	ID               int64
	ItineraryID      int64
	PassengerID      int64
	FlightInstanceID int64
	Seat             string
}
