// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Airport struct {
	ID       int64
	IataCode string
}

type Flight struct {
	ID                 int64
	Number             string
	OriginAirport      int64
	DestinationAirport int64
	Published          bool
}
