// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createAirline = `-- name: CreateAirline :one
INSERT INTO airlines (
  iata_code,
  name
) VALUES (
  ?, ?
)
RETURNING id, iata_code, name
`

type CreateAirlineParams struct {
	IataCode string
	Name     string
}

func (q *Queries) CreateAirline(ctx context.Context, arg CreateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, createAirline, arg.IataCode, arg.Name)
	var i Airline
	err := row.Scan(&i.ID, &i.IataCode, &i.Name)
	return i, err
}

const createAirport = `-- name: CreateAirport :one
INSERT INTO airports (
  iata_code,
  oadb_id
) VALUES (
  ?, ?
)
RETURNING id, iata_code, oadb_id
`

type CreateAirportParams struct {
	IataCode string
	OadbID   sql.NullInt64
}

func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) (Airport, error) {
	row := q.db.QueryRowContext(ctx, createAirport, arg.IataCode, arg.OadbID)
	var i Airport
	err := row.Scan(&i.ID, &i.IataCode, &i.OadbID)
	return i, err
}

const createFlight = `-- name: CreateFlight :one
INSERT INTO flights (
  airline_id, number, origin_airport_id, destination_airport_id, published
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id
`

type CreateFlightParams struct {
	AirlineID            int64
	Number               string
	OriginAirportID      int64
	DestinationAirportID int64
	Published            bool
}

func (q *Queries) CreateFlight(ctx context.Context, arg CreateFlightParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createFlight,
		arg.AirlineID,
		arg.Number,
		arg.OriginAirportID,
		arg.DestinationAirportID,
		arg.Published,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteAirline = `-- name: DeleteAirline :exec
DELETE FROM airlines
WHERE id=?
`

func (q *Queries) DeleteAirline(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAirline, id)
	return err
}

const deleteAirport = `-- name: DeleteAirport :exec
DELETE FROM airports
WHERE id=?
`

func (q *Queries) DeleteAirport(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAirport, id)
	return err
}

const deleteAllAirlines = `-- name: DeleteAllAirlines :exec
DELETE FROM airlines
`

func (q *Queries) DeleteAllAirlines(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAirlines)
	return err
}

const deleteAllAirports = `-- name: DeleteAllAirports :exec
DELETE FROM airports
`

func (q *Queries) DeleteAllAirports(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAirports)
	return err
}

const deleteAllFlights = `-- name: DeleteAllFlights :exec
DELETE FROM flights
`

func (q *Queries) DeleteAllFlights(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFlights)
	return err
}

const deleteFlight = `-- name: DeleteFlight :exec
DELETE FROM flights
WHERE id=?
`

func (q *Queries) DeleteFlight(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlight, id)
	return err
}

const getAirline = `-- name: GetAirline :one

SELECT id, iata_code, name FROM airlines
WHERE id=? LIMIT 1
`

// ----------------------------------------------------------------------------- airlines
func (q *Queries) GetAirline(ctx context.Context, id int64) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirline, id)
	var i Airline
	err := row.Scan(&i.ID, &i.IataCode, &i.Name)
	return i, err
}

const getAirlineByIATACode = `-- name: GetAirlineByIATACode :one
SELECT id, iata_code, name FROM airlines
WHERE iata_code=? LIMIT 1
`

func (q *Queries) GetAirlineByIATACode(ctx context.Context, iataCode string) (Airline, error) {
	row := q.db.QueryRowContext(ctx, getAirlineByIATACode, iataCode)
	var i Airline
	err := row.Scan(&i.ID, &i.IataCode, &i.Name)
	return i, err
}

const getAirport = `-- name: GetAirport :one

SELECT id, iata_code, oadb_id FROM airports
WHERE id=? LIMIT 1
`

// ----------------------------------------------------------------------------- airports
func (q *Queries) GetAirport(ctx context.Context, id int64) (Airport, error) {
	row := q.db.QueryRowContext(ctx, getAirport, id)
	var i Airport
	err := row.Scan(&i.ID, &i.IataCode, &i.OadbID)
	return i, err
}

const getAirportByIATACode = `-- name: GetAirportByIATACode :one
SELECT id, iata_code, oadb_id FROM airports
WHERE iata_code=? LIMIT 1
`

func (q *Queries) GetAirportByIATACode(ctx context.Context, iataCode string) (Airport, error) {
	row := q.db.QueryRowContext(ctx, getAirportByIATACode, iataCode)
	var i Airport
	err := row.Scan(&i.ID, &i.IataCode, &i.OadbID)
	return i, err
}

const getFlight = `-- name: GetFlight :one

SELECT id, airline_id, number, origin_airport_id, destination_airport_id, published, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, airline_iata_code, airline_name FROM flights_view
WHERE id=? LIMIT 1
`

// ----------------------------------------------------------------------------- flights
func (q *Queries) GetFlight(ctx context.Context, id int64) (FlightsView, error) {
	row := q.db.QueryRowContext(ctx, getFlight, id)
	var i FlightsView
	err := row.Scan(
		&i.ID,
		&i.AirlineID,
		&i.Number,
		&i.OriginAirportID,
		&i.DestinationAirportID,
		&i.Published,
		&i.OriginAirportIataCode,
		&i.OriginAirportOadbID,
		&i.DestinationAirportIataCode,
		&i.DestinationAirportOadbID,
		&i.AirlineIataCode,
		&i.AirlineName,
	)
	return i, err
}

const getRouteByIATACodes = `-- name: GetRouteByIATACodes :one

SELECT origin_airport_id, destination_airport_id, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, flights_count FROM routes
WHERE origin_airport_iata_code=?1 AND destination_airport_iata_code=?2
LIMIT 1
`

type GetRouteByIATACodesParams struct {
	OriginAirportIataCode      string
	DestinationAirportIataCode string
}

// ----------------------------------------------------------------------------- routes
func (q *Queries) GetRouteByIATACodes(ctx context.Context, arg GetRouteByIATACodesParams) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByIATACodes, arg.OriginAirportIataCode, arg.DestinationAirportIataCode)
	var i Route
	err := row.Scan(
		&i.OriginAirportID,
		&i.DestinationAirportID,
		&i.OriginAirportIataCode,
		&i.OriginAirportOadbID,
		&i.DestinationAirportIataCode,
		&i.DestinationAirportOadbID,
		&i.FlightsCount,
	)
	return i, err
}

const listAirlines = `-- name: ListAirlines :many
SELECT id, iata_code, name FROM airlines
ORDER BY id ASC
`

func (q *Queries) ListAirlines(ctx context.Context) ([]Airline, error) {
	rows, err := q.db.QueryContext(ctx, listAirlines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airline
	for rows.Next() {
		var i Airline
		if err := rows.Scan(&i.ID, &i.IataCode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAirports = `-- name: ListAirports :many
SELECT id, iata_code, oadb_id FROM airports
ORDER BY id ASC
`

func (q *Queries) ListAirports(ctx context.Context) ([]Airport, error) {
	rows, err := q.db.QueryContext(ctx, listAirports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airport
	for rows.Next() {
		var i Airport
		if err := rows.Scan(&i.ID, &i.IataCode, &i.OadbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlights = `-- name: ListFlights :many
SELECT id, airline_id, number, origin_airport_id, destination_airport_id, published, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, airline_iata_code, airline_name FROM flights_view
ORDER BY id ASC
`

func (q *Queries) ListFlights(ctx context.Context) ([]FlightsView, error) {
	rows, err := q.db.QueryContext(ctx, listFlights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightsView
	for rows.Next() {
		var i FlightsView
		if err := rows.Scan(
			&i.ID,
			&i.AirlineID,
			&i.Number,
			&i.OriginAirportID,
			&i.DestinationAirportID,
			&i.Published,
			&i.OriginAirportIataCode,
			&i.OriginAirportOadbID,
			&i.DestinationAirportIataCode,
			&i.DestinationAirportOadbID,
			&i.AirlineIataCode,
			&i.AirlineName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlightsByAirline = `-- name: ListFlightsByAirline :many
SELECT id, airline_id, number, origin_airport_id, destination_airport_id, published, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, airline_iata_code, airline_name
FROM flights_view
WHERE airline_id=?1
ORDER BY id ASC
`

func (q *Queries) ListFlightsByAirline(ctx context.Context, airline int64) ([]FlightsView, error) {
	rows, err := q.db.QueryContext(ctx, listFlightsByAirline, airline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightsView
	for rows.Next() {
		var i FlightsView
		if err := rows.Scan(
			&i.ID,
			&i.AirlineID,
			&i.Number,
			&i.OriginAirportID,
			&i.DestinationAirportID,
			&i.Published,
			&i.OriginAirportIataCode,
			&i.OriginAirportOadbID,
			&i.DestinationAirportIataCode,
			&i.DestinationAirportOadbID,
			&i.AirlineIataCode,
			&i.AirlineName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlightsByAirport = `-- name: ListFlightsByAirport :many
SELECT id, airline_id, number, origin_airport_id, destination_airport_id, published, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, airline_iata_code, airline_name
FROM flights_view
WHERE origin_airport_id=?1 OR destination_airport_id=?1
ORDER BY id ASC
`

func (q *Queries) ListFlightsByAirport(ctx context.Context, airport int64) ([]FlightsView, error) {
	rows, err := q.db.QueryContext(ctx, listFlightsByAirport, airport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightsView
	for rows.Next() {
		var i FlightsView
		if err := rows.Scan(
			&i.ID,
			&i.AirlineID,
			&i.Number,
			&i.OriginAirportID,
			&i.DestinationAirportID,
			&i.Published,
			&i.OriginAirportIataCode,
			&i.OriginAirportOadbID,
			&i.DestinationAirportIataCode,
			&i.DestinationAirportOadbID,
			&i.AirlineIataCode,
			&i.AirlineName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlightsByRoute = `-- name: ListFlightsByRoute :many
SELECT id, airline_id, number, origin_airport_id, destination_airport_id, published, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, airline_iata_code, airline_name
FROM flights_view
WHERE origin_airport_id=?1 OR destination_airport_id=?2
ORDER BY id ASC
`

type ListFlightsByRouteParams struct {
	OriginAirport      int64
	DestinationAirport int64
}

func (q *Queries) ListFlightsByRoute(ctx context.Context, arg ListFlightsByRouteParams) ([]FlightsView, error) {
	rows, err := q.db.QueryContext(ctx, listFlightsByRoute, arg.OriginAirport, arg.DestinationAirport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlightsView
	for rows.Next() {
		var i FlightsView
		if err := rows.Scan(
			&i.ID,
			&i.AirlineID,
			&i.Number,
			&i.OriginAirportID,
			&i.DestinationAirportID,
			&i.Published,
			&i.OriginAirportIataCode,
			&i.OriginAirportOadbID,
			&i.DestinationAirportIataCode,
			&i.DestinationAirportOadbID,
			&i.AirlineIataCode,
			&i.AirlineName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT origin_airport_id, destination_airport_id, origin_airport_iata_code, origin_airport_oadb_id, destination_airport_iata_code, destination_airport_oadb_id, flights_count FROM routes
ORDER BY flights_count DESC, origin_airport_id ASC, destination_airport_id ASC
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.OriginAirportID,
			&i.DestinationAirportID,
			&i.OriginAirportIataCode,
			&i.OriginAirportOadbID,
			&i.DestinationAirportIataCode,
			&i.DestinationAirportOadbID,
			&i.FlightsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirline = `-- name: UpdateAirline :one
UPDATE airlines SET
iata_code = COALESCE(?2, iata_code),
name = COALESCE(?3, name)
WHERE id=?
RETURNING id, iata_code, name
`

type UpdateAirlineParams struct {
	IataCode sql.NullString
	Name     sql.NullString
	ID       int64
}

func (q *Queries) UpdateAirline(ctx context.Context, arg UpdateAirlineParams) (Airline, error) {
	row := q.db.QueryRowContext(ctx, updateAirline, arg.IataCode, arg.Name, arg.ID)
	var i Airline
	err := row.Scan(&i.ID, &i.IataCode, &i.Name)
	return i, err
}

const updateAirport = `-- name: UpdateAirport :one
UPDATE airports SET
iata_code = COALESCE(?2, iata_code)
WHERE id=?
RETURNING id, iata_code, oadb_id
`

type UpdateAirportParams struct {
	IataCode sql.NullString
	ID       int64
}

func (q *Queries) UpdateAirport(ctx context.Context, arg UpdateAirportParams) (Airport, error) {
	row := q.db.QueryRowContext(ctx, updateAirport, arg.IataCode, arg.ID)
	var i Airport
	err := row.Scan(&i.ID, &i.IataCode, &i.OadbID)
	return i, err
}

const updateFlight = `-- name: UpdateFlight :one
UPDATE flights SET
airline_id = COALESCE(?1, airline_id),
number = COALESCE(?2, number),
origin_airport_id = COALESCE(?3, origin_airport_id),
destination_airport_id = COALESCE(?4, destination_airport_id),
published = COALESCE(?5, published)
WHERE id=?6
RETURNING id
`

type UpdateFlightParams struct {
	AirlineID            sql.NullInt64
	Number               sql.NullString
	OriginAirportID      sql.NullInt64
	DestinationAirportID sql.NullInt64
	Published            sql.NullBool
	ID                   int64
}

func (q *Queries) UpdateFlight(ctx context.Context, arg UpdateFlightParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateFlight,
		arg.AirlineID,
		arg.Number,
		arg.OriginAirportID,
		arg.DestinationAirportID,
		arg.Published,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
